model:
  model_name: "wide_resnet50_2"
  from_torchvision: True
  input_shape: [3, 320, 320] 
  bottleneck_dim: 256
  weight_norm: True
  bias: True
  n_classes: 3

data:
  pad: [40, 0, 40, 0]  # left, top, right and bottom 
  resize_size: [320, 320]
  crop_size: [320, 320]
  mean: [0.5, 0.5, 0.5] 
  std:  [0.229, 0.224, 0.225]